### ISSUE TITLE
Can't locate IO/Socket/Socks.pm

### ISSUE THREAD

**Issue by Beyarz** [MustLive/DAVOSET#2]
D:\DAVOSET-master>davoset.pl

Can't locate IO/Socket/Socks.pm in @INC (you may need to install the IO::Socket::Socks module) (@INC contains: C:/Perl64/site/lib C:/Perl64/lib .) at D:\DAVOSET-master\davoset.pl line 32.
BEGIN failed--compilation aborted at D:\DAVOSET-master\davoset.pl line 32.

**Comment by MustLive** [comment]
I have answered already https://github.com/MustLive/DAVOSET/issues/1.

**Comment by Beyarz** [comment]
Oh my bad, saw it now.
